### ISSUE TITLE
Open iterm2?

### ISSUE THREAD

**Issue by timothyylim** [blueimp/atom-open-terminal-here#12]
Great plugin! Is there any way to open iterm2 instead?

**Comment by blueimp** [comment]
Sure!

In the Settings of the package, this is the default `Command` config:

``` sh
open -a Terminal.app "$PWD"
```

Simply change it to the following to open iTerm2 instead:

``` sh
open -a iTerm.app "$PWD"
```

**Comment by timothyylim** [comment]
Perfect. Thanks.

**Comment by blueimp** [comment]
You're welcome. :)

**Comment by Jiiiiiin** [comment]
thax @blueimp
