### ISSUE TITLE
keyboard shortcut only opens at parent dir not selected dir

### ISSUE THREAD

**Issue by Asynchronous003** [blueimp/atom-open-terminal-here#14]
right click menu option works as expected but keyboard shortcut does not respect selected file.
OS Kali rolling 64bit
Desktop Cinnamon 3.2.7
Gnome terminal
Atom 1.13.0

**Comment by blueimp** [comment]
Thanks for your report, @Asynchronous003 
Could you provide some further details?
Selecting a file in the file tree of Atom and then hitting `ctrl-alt-t` does not open the Gnome terminal in the expected directory?

**Comment by Asynchronous003** [comment]
Hi, yes I will try to explain(great plug-in by the way, thanks). 
So the keyboard shortcut method, requires that you click on a file inside a folder, for the terminal to open into that folder, yet the right click method only requires that the folder be moused over to select it.
On reflection, I can see that this may be intended behavior, the same as a regular file browser, only clicking inside an empty folder isn't possible in the file tree.
 So to open a terminal inside an empty folder, first a file needs to be created in the folder so it can be opened, so the terminal can be opened in said folder. If possible, it would be great if when the folder in the tree view is highlighted, the terminal opens inside that folder. Bug or not?
Thanks again :)

**Comment by blueimp** [comment]
Thanks for the explanation. Yes, this was a bug which has now been fixed. :)

**Comment by Asynchronous003** [comment]
Legend!
