### ISSUE TITLE
[Feature Request] Let user specify their own terminal

### ISSUE THREAD

**Issue by pingshunhuangalex** [blueimp/atom-open-terminal-here#15]
Is it possible to specify your own terminal to open? Personally, I use `Git Bash` for my Windows10 laptop, but with this package, I can only open windows command, not even powershell...

Meanwhile, if you can change the text in the context menu back to `open terminal here` instead of being specific as `open cmd prompt here`, it would be great. Thanks.

**Comment by pingshunhuangalex** [comment]
That's not what I mean though... (well partly.)

**Comment by blueimp** [comment]
Actually yes, sorry, after pushing this commit I noticed that the settings view is not accessible anymore for this package. I'll look into it.

**Comment by blueimp** [comment]
OK, the reason I couldn't see the settings view was that the package was linked into my `~/.atom/packages/` folder with a symlink.
After installing it via conventional means, the settings view was visible.

In the settings view, you should be able to override the default command (`start /D "%cd%" cmd` on windows).
