### ISSUE TITLE
Does not work on Linux Mint 18.3 Sylvia x64 Cinnamon

### ISSUE THREAD

**Issue by smuroff** [blueimp/atom-open-terminal-here#22]
OS: Mint 18.3 Sylvia x64 with Cinnamon
Atom: 1.24.0 x64

Open-Terminal-Here package doesn't work at all (xdotool exists).

**Comment by blueimp** [comment]
xdotool is not required, since it's only used in the optional provided script for the "opening in new tab" option.

Does the `x-terminal-emulator` command exist on your platform?
And if not, which command does your platform provide to open a terminal?

**Comment by smuroff** [comment]
> Does the x-terminal-emulator command exist on your platform?

Yeah, sure.

> And if not, which command does your platform provide to open a terminal?

ctrl + alt + t as default.

**Comment by blueimp** [comment]
On Linux, this project simply calls `x-terminal-emulator`:
https://github.com/blueimp/atom-open-terminal-here/blob/master/index.coffee#L54

It does this with a relative directory set to the desired one:
https://github.com/blueimp/atom-open-terminal-here/blob/master/index.coffee#L46

If you have time you could try if you can reproduce the issue with doing the same thing with NodeJS directly, or having a go at debugging this project itself.

**Comment by blueimp** [comment]
@pr0minence, did you solve the problem?
