### ISSUE TITLE
Could I use gnome-terminal?

### ISSUE THREAD

**Issue by deweiwork** [blueimp/atom-open-terminal-here#26]
Hi :
I know the command of open the gnome-terminal in linux is 
"gnome-terminal --working-directory=/path/to/dir"

So I attempt to keying above command in package/open-terminal-here/setting/command.

It successfully open gnome-terminal, but directory is home, does not current directory.

Could I use gnome-terminal by it way?
Or have others way?

**Comment by deweiwork** [comment]
Hi  
This problem already solved.
Just keying gnome-terminal in package/open-terminal-here/setting/command.
And need to relaunch.

**Comment by blueimp** [comment]
Thanks for the update @deweiwork !
