### ISSUE TITLE
Open windows in tab (OS X)

### ISSUE THREAD

**Issue by jirsbek** [blueimp/atom-open-terminal-here#3]
Thank you for great package.

Little enhacement - would be nice if other window will open in new terminal tab instead of new window (OS X).

**Comment by blueimp** [comment]
This is possible with an OSX Automator app.
Please refer to the instructions [here](https://gist.github.com/blueimp/123c50a459800cdfa0ef#gistcomment-1546216).

**Comment by blueimp** [comment]
Update: I've moved the Gist into the official repo and added the instructions to the README.
