### ISSUE TITLE
Directory is ignored on linux (xfce)

### ISSUE THREAD

**Issue by phellmes** [blueimp/atom-open-terminal-here#4]
When I use "open terminal here" it opens a terminal but completely ignores the directory. The terminal always starts at home directory which is not the desired behavior.

It doesn't matter if I use it from the tree view or from an open file.

I'm on Linux Mint 17.1 with XFCE desktop.

**Comment by blueimp** [comment]
Which version of the plugin are you running?
I've just released v2.0.0 yesterday which fixes this issue on Ubuntu Linux.

**Comment by phellmes** [comment]
I've updated to v2.0.0 earlier but still had the issue. Now - after closing and starting again - it's gone. Thanks!

I noticed that the update didn't finish correctly after hitting the button - it kept going on and on but the package manager later said it was on v2.0.0 (maybe that caused the delay). I don't know if that's an issue with the packages (happens sometimes with different packages, first time with yours) or with atom itself.

But I'm happy that it works now because that saves me a lot of time.

**Comment by blueimp** [comment]
Thanks @phellmes!

I'm not sure what caused the delay in the update.
As a package developer, updating a package consists only of running a publish command which pushes the updates to GitHub and registers the new package in the Atom registry.
