### ISSUE TITLE
Option for opening terminal at project root?

### ISSUE THREAD

**Issue by jesseleite** [blueimp/atom-open-terminal-here#5]
Awesome package.  What do you think about adding an option + hotkey for opening terminal at project root, rather than at current file path?  I often find myself using your package then `../../../..` back to my folder root in terminal.

**Comment by blueimp** [comment]
Thanks for the suggestion, @JesseLeite.
The latest release adds additional keyboard shortcuts to always open the terminal in the root of the current project.

**Comment by jesseleite** [comment]
Beauty @blueimp, and thank you for such a fast response!
