### ISSUE TITLE
Open iTerm here?

### ISSUE THREAD

**Issue by damassi** [blueimp/atom-open-terminal-here#6]
Is this possible?

**Comment by blueimp** [comment]
Sure, you can basically use any terminal application you like, by configuring the `Command` setting (_Settings View: Installed Packages => Open Terminal Here_).

Here's the setting for [iTerm2](https://www.iterm2.com/) installed via Homebrew Cask:

``` sh
open -a $HOME/Applications/iTerm.app "$PWD"
```

**Comment by damassi** [comment]
Thanks!

**Comment by losbenos** [comment]
FSPathMakeRef (..path) failed with error -43.
Any idea what's causing this when I use the command above?
